/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminLoginRequest"];
                };
            };
            responses: {
                /** @description success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invite_codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List codes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InviteCode"][];
                    };
                };
            };
        };
        put?: never;
        /** Create code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with PIN */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register team */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: number;
            username: string;
            email?: string | null;
            /** @enum {string} */
            role: "teammate" | "team_lead";
            team_id: number;
            pin_reset_required?: boolean;
        };
        Team: {
            id: number;
            name: string;
            /** Format: date-time */
            created_at?: string;
            teammate_count: number;
            invite_code?: string | null;
            team_lead?: components["schemas"]["User"];
        };
        Book: {
            id: number;
            title: string;
            author?: string | null;
            team_id: number;
        };
        BookAssignment: {
            id: number;
            user_id: number;
            book_id: number;
            /** @enum {string} */
            status: "assigned" | "in_progress" | "completed";
            progress_notes?: string | null;
            book?: components["schemas"]["Book"];
        };
        InviteCode: {
            id: number;
            code: string;
            name: string;
            max_uses?: number | null;
            uses_count: number;
            /** Format: date-time */
            expires_at?: string | null;
            active: boolean;
            available: boolean;
        };
        LoginRequest: {
            username: string;
            team_id: number;
            pin_code: string;
        };
        AdminLoginRequest: {
            email: string;
            password: string;
        };
        RegisterRequest: {
            invite_code: string;
            team_name: string;
            username: string;
            email: string;
        };
        AuthResponse: {
            token: string;
            user: components["schemas"]["User"];
            team?: components["schemas"]["Team"];
            pin_reset_required?: boolean;
        };
        AdminAuthResponse: {
            token: string;
            admin: {
                id?: number;
                email?: string;
            };
        };
        Error: {
            error: string;
        };
        StatsResponse: {
            total_teams?: number;
            total_users?: number;
            total_assignments?: number;
            assignments_by_status?: {
                assigned?: number;
                in_progress?: number;
                completed?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
